name: Elite
favicon: null
layout_spectrum: 0.00889
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7b7b7b'
    - '#92053a'
    - '#000000'
    - '#ff0000'
    - '#550000'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
